/*
 * =======================================================================================
 * SCRIPT COMPLETO - SISTEMA DE GESTÃO DE FESTAS
 * Banco de Dados: PostgreSQL
 * Autor: Equipe Delasse
 * =======================================================================================
 */

-- =======================================================================================
-- 0. CONFIGURAÇÃO INICIAL E LIMPEZA (CUIDADO: APAGA DADOS EXISTENTES)
-- =======================================================================================

DROP SCHEMA IF EXISTS public CASCADE;
CREATE SCHEMA public;
GRANT ALL ON SCHEMA public TO postgres;
GRANT ALL ON SCHEMA public TO public;

-- Extensão necessária para gerar UUIDs (caso precise gerar no banco)
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- =======================================================================================
-- 1. CRIAÇÃO DAS TABELAS (DDL) - ITEM 3
-- =======================================================================================

CREATE TABLE enterprise (
	id uuid NOT NULL,
	address varchar(255) NULL,
	date_expiration timestamp(6) NULL,
	"document" varchar(255) NULL,
	email varchar(255) NULL,
	"name" varchar(255) NULL,
	phone_number varchar(255) NULL,
	url_image varchar(255) NULL,
	CONSTRAINT enterprise_pkey PRIMARY KEY (id)
);

CREATE TABLE users (
	"uuid" uuid NOT NULL,
	active bool NOT NULL,
	birthday date NULL,
	email varchar(255) NULL,
	"name" varchar(255) NULL,
	"password" varchar(255) NULL,
	phone varchar(255) NULL,
	username varchar(255) NULL,
	enterprise_id uuid NULL,
	CONSTRAINT users_pkey PRIMARY KEY (uuid),
	CONSTRAINT fkq4mfuh7m1440s6oym0d052cch FOREIGN KEY (enterprise_id) REFERENCES enterprise(id)
);

CREATE TABLE gallery (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(255) NULL,
	enterprise_id uuid NULL,
	CONSTRAINT gallery_pkey PRIMARY KEY (id),
	CONSTRAINT fktcmj1ujaffxfp1lt3netaplec FOREIGN KEY (enterprise_id) REFERENCES enterprise(id)
);

CREATE TABLE image (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	alt varchar(255) NULL,
	url varchar(255) NULL,
	gallery_id int8 NULL,
	CONSTRAINT image_pkey PRIMARY KEY (id),
	CONSTRAINT fkgmnxnktphh1jne2xvnv5mwaom FOREIGN KEY (gallery_id) REFERENCES gallery(id)
);

CREATE TABLE party (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	description varchar(255) NULL,
	generate_budget float8 NULL,
	img_example varchar(255) NULL,
	last_atualization timestamp(6) NULL,
	observations varchar(255) NULL,
	status varchar(255) NULL,
	title varchar(255) NULL,
	enterprise_id uuid NULL,
	gallery_id int8 NULL,
	user_id uuid NULL,
	CONSTRAINT party_pkey PRIMARY KEY (id),
	CONSTRAINT fk4f8fsdyl39fnvgpmopiumn36c FOREIGN KEY (gallery_id) REFERENCES gallery(id),
	CONSTRAINT fk55it38pdf6kmmhse56lblyilo FOREIGN KEY (enterprise_id) REFERENCES enterprise(id),
	CONSTRAINT fkovyvfds7dj7unwvquf3687j3i FOREIGN KEY (user_id) REFERENCES users("uuid")
);

CREATE TABLE product (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	category varchar(255) NULL,
	date_create timestamp(6) NULL,
	date_update timestamp(6) NULL,
	description varchar(255) NULL,
	image_url varchar(255) NULL,
	"name" varchar(255) NULL,
	price float8 NULL,
	stock_quantity int4 NULL,
	enterprise_id uuid NULL,
	user_id uuid NULL,
	CONSTRAINT product_pkey PRIMARY KEY (id),
	CONSTRAINT fk47nyv78b35eaufr6aa96vep6n FOREIGN KEY (user_id) REFERENCES users("uuid"),
	CONSTRAINT fkjwmrglutt30rkt9uqi30ulovh FOREIGN KEY (enterprise_id) REFERENCES enterprise(id)
);

CREATE TABLE party_products (
	party_id int8 NOT NULL,
	product_id int8 NOT NULL,
	CONSTRAINT fkm8es3qq9mnfctwk75vvubrv4b FOREIGN KEY (party_id) REFERENCES party(id),
	CONSTRAINT fkqj85jvpkgyfj5dtleblnrivea FOREIGN KEY (product_id) REFERENCES product(id)
);

CREATE TABLE cart (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	total_price float8 NOT NULL,
	enterprise_id uuid NULL,
	party_id int8 NULL,
	user_id uuid NULL,
	CONSTRAINT cart_pkey PRIMARY KEY (id),
	CONSTRAINT fkdhbd6j06y32m0wywoxsh21pe5 FOREIGN KEY (enterprise_id) REFERENCES enterprise(id),
	CONSTRAINT fkg5uhi8vpsuy0lgloxk2h4w5o6 FOREIGN KEY (user_id) REFERENCES users("uuid"),
	CONSTRAINT fkia3nwl0r2oocnikrpy8jhefmo FOREIGN KEY (party_id) REFERENCES party(id)
);

CREATE TABLE "role" (
	role_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(255) NOT NULL,
	CONSTRAINT role_pkey PRIMARY KEY (role_id),
	CONSTRAINT uk8sewwnpamngi6b1dwaa88askk UNIQUE (name)
);

CREATE TABLE user_roles (
	user_id uuid NOT NULL,
	role_id int8 NOT NULL,
	CONSTRAINT fkhfh9dx7w3ubf1co1vdev94g3f FOREIGN KEY (user_id) REFERENCES users("uuid"),
	CONSTRAINT fkrhfovtciq1l558cw6udg0h0d3 FOREIGN KEY (role_id) REFERENCES "role"(role_id)
);

-- Tabela extra para Log de Auditoria (Necessária para o Trigger)
CREATE TABLE product_price_audit (
    audit_id SERIAL PRIMARY KEY,
    product_id int8 NOT NULL,
    old_price float8,
    new_price float8,
    changed_at timestamp DEFAULT CURRENT_TIMESTAMP,
    changed_by varchar(255) DEFAULT current_user
);

-- =======================================================================================
-- 2. MELHORIAS, ÍNDICES E CONSTRAINTS EXTRAS - ITEM 3
-- =======================================================================================

-- Constraints de verificação (Check Constraints)
ALTER TABLE product ADD CONSTRAINT chk_product_price_positive CHECK (price >= 0);
ALTER TABLE product ADD CONSTRAINT chk_product_stock_positive CHECK (stock_quantity >= 0);
ALTER TABLE cart ADD CONSTRAINT chk_cart_total_positive CHECK (total_price >= 0);

-- Índices para melhorar performance de JOINS
CREATE INDEX idx_party_user ON party(user_id);
CREATE INDEX idx_party_enterprise ON party(enterprise_id);
CREATE INDEX idx_cart_user ON cart(user_id);
CREATE INDEX idx_cart_enterprise ON cart(enterprise_id);
CREATE INDEX idx_product_category ON product(category);
CREATE INDEX idx_users_email ON users(email);

-- =======================================================================================
-- 3. VIEWS (RELATÓRIOS) - ITEM 2
-- =======================================================================================

-- View 1: Relatório de Orçamento vs Custo Real
-- Mostra se a festa está dentro ou fora do orçamento planejado
CREATE OR REPLACE VIEW vw_relatorio_orcamento AS
SELECT 
    p.title AS festa,
    u.name AS cliente,
    p.generate_budget AS orcamento_inicial,
    COALESCE(SUM(prod.price), 0) AS custo_atual,
    (p.generate_budget - COALESCE(SUM(prod.price), 0)) AS saldo_disponivel,
    CASE 
        WHEN (p.generate_budget - COALESCE(SUM(prod.price), 0)) < 0 THEN 'ESTOUROU'
        ELSE 'DENTRO DO PRAZO'
    END AS status_financeiro
FROM party p
JOIN users u ON p.user_id = u.uuid
LEFT JOIN party_products pp ON p.id = pp.party_id
LEFT JOIN product prod ON pp.product_id = prod.id
GROUP BY p.id, p.title, u.name, p.generate_budget;

-- View 2: Relatório de Performance de Vendas por Empresa
CREATE OR REPLACE VIEW vw_performance_empresas AS
SELECT 
    e.name AS empresa,
    COUNT(c.id) AS qtd_vendas,
    COALESCE(SUM(c.total_price), 0) AS faturamento_total
FROM enterprise e
LEFT JOIN cart c ON c.enterprise_id = e.id
GROUP BY e.id, e.name
ORDER BY faturamento_total DESC;

-- =======================================================================================
-- 4. PROCEDURES (PROCEDIMENTOS ARMAZENADOS) - ITEM 6
-- =======================================================================================

-- Procedure 1: Reajuste de Preços em Massa
-- Aplica uma porcentagem de aumento ou desconto em toda uma categoria
CREATE OR REPLACE PROCEDURE sp_reajustar_precos(
    p_categoria VARCHAR, 
    p_percentual FLOAT
)
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE product
    SET price = price + (price * (p_percentual / 100)),
        date_update = NOW()
    WHERE category = p_categoria;
END;
$$;

-- Procedure 2: Transferência de Festa entre Usuários
-- Útil se um organizador sair e outro assumir
CREATE OR REPLACE PROCEDURE sp_transferir_festa(
    p_party_id INT8,
    p_novo_user_uuid UUID
)
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE party
    SET user_id = p_novo_user_uuid,
        last_atualization = NOW()
    WHERE id = p_party_id;
END;
$$;

-- =======================================================================================
-- 5. GATILHOS (TRIGGERS) - ITEM 5
-- =======================================================================================

-- Trigger 1: Auditoria de Preço
-- Salva o preço antigo na tabela de log sempre que houver alteração
CREATE OR REPLACE FUNCTION fn_audit_product_price()
RETURNS TRIGGER AS $$
BEGIN
    IF OLD.price <> NEW.price THEN
        INSERT INTO product_price_audit (product_id, old_price, new_price)
        VALUES (OLD.id, OLD.price, NEW.price);
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_audit_price
AFTER UPDATE ON product
FOR EACH ROW
EXECUTE FUNCTION fn_audit_product_price();

-- Trigger 2: Atualização Automática de 'last_atualization' e 'date_update'
-- Garante que o campo de data de modificação esteja sempre correto
CREATE OR REPLACE FUNCTION fn_update_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    -- Se a tabela tiver coluna last_atualization (party)
    IF (TG_TABLE_NAME = 'party') THEN
        NEW.last_atualization = CURRENT_TIMESTAMP;
    -- Se a tabela tiver coluna date_update (product)
    ELSIF (TG_TABLE_NAME = 'product') THEN
        NEW.date_update = CURRENT_TIMESTAMP;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_update_party_timestamp
BEFORE UPDATE ON party
FOR EACH ROW
EXECUTE FUNCTION fn_update_timestamp();

CREATE TRIGGER trg_update_product_timestamp
BEFORE UPDATE ON product
FOR EACH ROW
EXECUTE FUNCTION fn_update_timestamp();

-- =======================================================================================
-- 6. POLÍTICAS DE ACESSO (DCL) - ITEM 4
-- =======================================================================================

DO $$
BEGIN
    -- Tenta criar os roles se não existirem
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'grupo_admin') THEN
        CREATE ROLE grupo_admin;
    END IF;
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'grupo_relatorios') THEN
        CREATE ROLE grupo_relatorios;
    END IF;
END
$$;

-- Permissões para Admin (Controle Total)
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO grupo_admin;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO grupo_admin;

-- Permissões para Grupo de Relatórios (Apenas Leitura)
GRANT SELECT ON ALL TABLES IN SCHEMA public TO grupo_relatorios;
-- Especificamente acesso às Views criadas
GRANT SELECT ON vw_relatorio_orcamento TO grupo_relatorios;
GRANT SELECT ON vw_performance_empresas TO grupo_relatorios;